name: "build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # job 1: Test based on java 8 and 21. Do not checkstyle.
  build:
    name: "build"
    services:
      aerospike:
        image: aerospike/aerospike-server:7.0.0.7_1
        ports:
          - 3000:3000
          - 3001:3001
          - 3002:3002
          - 3003:3003
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 8, 21 ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Set up Java JDK"
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: "Print maven version"
        run: ./mvnw -version
      - name: "Test, Check style, Check PMD, Check license with Maven and Java"
        run: |
          ./mvnw -T 4C clean test && sh ./tools/check_format.sh
      - name: "Codecov"
        if: matrix.java == '8'
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}